#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npx tsc --noEmit && npx eslint --fix . && npx prettier --write

npx lint-staged ||
(
  echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
          lint-staged Failed. try commit again.';
  false;
)
