#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npx tsc --noEmit && npx eslint --fix . && npx prettier --write

npm run lint ||
(
  echo '🤢🤮🤢🤮 Its F**KING RAW - Your code looks disgusting because not follow eslint. 🤢🤮🤢🤮
          lint Failed. try commit again.';
  false;
)
